transport-layer-type=HPS
require-iid-uds=true
test-mode-secrets=false
accept-unsigned-corim=false
lib-spdm-params.wrapper-library-path=
lib-spdm-params.ct-exponent=
lib-spdm-params.measurements-request-signature=
database-configuration.internal-database=true
verifier-key-params.verifier-root-qky-chain.single-chain-path=
verifier-key-params.verifier-root-qky-chain.multi-chain-path=
verifier-key-params.key-name=
distribution-point.main-path=https://tsci.altera.com/
distribution-point.attestation-cert-base-path=content/IPCS/certs/
distribution-point.trusted-root-hash=\
  99B95D7EF5A42B26758F959C9F7BDC5E473AC5D50A3484BC96E7E587D3C328CC
distribution-point.proxy.host=
distribution-point.proxy.port=
security-provider-params.provider.name=BC
security-provider-params.provider.file-based=true
security-provider-params.provider.class-name=org.bouncycastle.jce.provider.BouncyCastleProvider
security-provider-params.security.key-store-name=uber
security-provider-params.security.password=
security-provider-params.security.input-stream-param=/tmp/bc-keystore-verifier.jks
security-provider-params.key-types.ec.key-name=EC
security-provider-params.key-types.ec.curve-spec-384=secp384r1
security-provider-params.key-types.ec.curve-spec-256=secp256r1
security-provider-params.key-types.ec.signature-algorithm=SHA384withECDSA
truststore.location=/tmp/verifier-nonprod.p12
truststore.password=donotchange
truststore.type=PKCS12
